require("setup/transparent")
require("setup/comment")
require("setup/osc52")
require("setup/neoclip")
require("setup/indent_blankline")
require("setup/telescope")
require("setup/treesitter")
require("setup/cmp")
require("setup/dap")
require("setup/lsp")
require("setup/easydotnet")
require("setup/godotdev")

require("lualine").setup()
